### ISSUE TITLE
ALPS-Gutenberg-Blocks does not update automatically

### ISSUE THREAD

**Issue by cdbieling** [adventistchurch/alps-gutenberg-blocks#20]
I worked with ALPS-Gutenberg-Block v.1.0.0. 
Because there were missing a lot of Blocks, i investigated, and saw, that the alps-gutenberg-block plugin have not been updated with the themes update process. 
I just want to report this issue, I don't know, if this is a singular case. I will observer this, if i get an update notification of future plugin update releases.

**Comment by designerbrent** [comment]
@dbieling It should update, or show as an update, like any other plugin. We can't control when your Wordpress install updates plugins, unfortunately, so you will have to make sure your plugins are uploaded to ensure you have the latest version.
