### ISSUE TITLE
Bugs with Pasting in ALPS Gutenberg Blocks

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#25]
## Problem 
After working with @kelscahill on the Media Testimonies Block, we found that there is an [issue with not being able to paste when the `isSelected: false` property is set.](https://github.com/adventistchurch/alps-gutenberg-blocks/pull/24#issuecomment-621804226_) 

## Solution:

We need to make sure that the following blocks can all have text pasted into them:

- [x] ALPS Blockquote
- [x] ALPS CTA
- [x] ALPS Content Block
- [x] ALPS Accordion
- [x] ALPS Content Expand
- [x] ALPS Content Show More

**Comment by kelscahill** [comment]
@designerbrent All these issue are updated and within this PR: https://github.com/adventistchurch/alps-gutenberg-blocks/pull/28
