### ISSUE TITLE
Add limited text styling on selected blocks

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#26]
## Problem 
Some ALPS blocks support a limited styled text (`ALPS Highlighted Paragraph`) but many that need it do not. This results in some extra work and inconsistencies. 

## Solution
Enable limited styling of text in the following blocks: 

- [x] ALPS Accordion 
- [x] ALPS CTA description field
- [x] ALPS Content Block description field
- [x] ALPS Content Expand description field
- [x] ALPS Content Show More description field
- [x] ALPS Content Show More body field

**Comment by kelscahill** [comment]
@designerbrent All these issue are updated and within this PR: https://github.com/adventistchurch/alps-gutenberg-blocks/pull/28
