### ISSUE TITLE
Interface Issue with ALPS Content Expand

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#27]
## Problem
While editing, it is hard to see where one field begins and one ends. Additionally, it is impossible to style the text entered in the body of the block.
![2020-05-05 at 4 19 PM](https://user-images.githubusercontent.com/132864/81112159-39b7e300-8eec-11ea-8b40-32a4e7d4f871.png)

## Solution Story 
- [x] User should see a clear view of the fields of a block.
- [x] User should be able to paste text into any field on the block. (Also mentioned in #25)
- [x] User should be able to style the text like you can with *ALPS Highlighted Paragraph*  (Also mentioned in #26)

**Comment by kelscahill** [comment]
@designerbrent All these issue are updated and within this PR: https://github.com/adventistchurch/alps-gutenberg-blocks/pull/28
