### ISSUE TITLE
Refactor blocks

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#37]
After review by @sergsadovyi, we found that the blocks will need to be refactored to improve maintainability and reliability in the future. 

The blocks in question are: 

- [x] accordion
- [x] blockquote
- [x] content-block
- [x] content-expand
- [x] content-show-more
- [x] highlighted-paragraph
- [x] image-breakout
- [x] image-2up
- [x] gallery
- [x] latest-posts
- [x] media-testimonies
- [x] media-testimony
- [x] cta

**Comment by YauheniKapliarchuk** [comment]
Hi @sergsadovyi @designerbrent ,

Do we really need refactoring Content-Expand block, because it looks like the new one Inline-Sidebar?

Thanks

**Comment by designerbrent** [comment]
It may not need to be refactored.

**Comment by YauheniKapliarchuk** [comment]
Just for update information about this ticket

PR -
https://github.com/adventistchurch/alps-gutenberg-blocks/pull/52

I thing we can close this ticket
