### ISSUE TITLE
V3 Download-Block is missing

### ISSUE THREAD

**Issue by cdbieling** [adventistchurch/alps-gutenberg-blocks#4]
Within Article, the Gutenberg-Download Block is not available `<!-- wp:download /-->`

**Comment by designerbrent** [comment]
@dbieling Could you clarify what you mean? I thought I knew, but on further investigation, I don't see a `Download` button a Gutenberg block.

**Comment by cdbieling** [comment]
Sorry, i was used to work on standard wordpress installs with gutenbergs attachment or (file)-Block. Its a specific block, for download-purpose. But as mentioned, adventistchurch/alps-wordpress#320 there seems no big difference, to the simple button-block. thanks to @kelscahill 

![Bildschirmfoto 2019-05-26 um 19 46 45](https://user-images.githubusercontent.com/19514133/58385402-2d46bd00-7ff0-11e9-9030-77c4fac8d7b0.png)
