### ISSUE TITLE
ALPS Gutenberg Block with 5-grid-layout

### ISSUE THREAD

**Issue by cdbieling** [adventistchurch/alps-gutenberg-blocks#47]
Is there a possibility, to use this Block on the Startpage without the Sidebar. (So that it uses without the Sidebar 5 instead of 4 columns?

See on the attachment below. One module on startpage uses 5-grid, one 4-grid.
![Bildschirmfoto 2020-11-08 um 18 16 43](https://user-images.githubusercontent.com/19514133/98471721-91fad500-21ee-11eb-8abb-b9d42a7fe07e.png)

**Comment by designerbrent** [comment]
In this example, the page is setup to use the middle 4 columns and leave a padding on the left and right. Is your question about why the lower block is only spanning 3 columns? Or are you wanting everything to span right 5 columns?

**Comment by cdbieling** [comment]
Yes. 
I think, the ALPS Latest post-Block spans 3 Columns only, because usually, there is a sidebar. But without Sidebar, it makes no sense, that this Block spans only 3 Columns, because every other Column spans the whole 5-Grid-layout. ("Youtube", "ALPS Content Show More", "Sermon Manager", "Instagram" and so on. 

The 3-Column Layout breaks the structure or the whole page.

**Comment by designerbrent** [comment]
Issue moved to [adventistchurch/alps-wordpress #546](https://github.com/adventistchurch/alps-wordpress/issues/546) via [**ZenHub**](https://www.zenhub.com/)
