### ISSUE TITLE
Video-Block Embed from URL does not work

### ISSUE THREAD

**Issue by cdbieling** [adventistchurch/alps-gutenberg-blocks#5]
I tried to insert a video with Gutenberg-Video-Block. Tried to insert Youtube-URL. But nothing happens after insertion. I tried with the same browser and same url on standard wordpress install, and it worked. It seems to be an ALPS issue. 

Interesting to know. On standard wordpress, there is an explicit Youtube-Block. Don't know, if this is the solution for ALPS, to add this block.

**Comment by designerbrent** [comment]
This appears to be working now and has been for a while. Try the `Embed` block.
