### ISSUE TITLE
Missing front.js file

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#59]
With version `1.9.0`, the `front.js` file is returning a 404. You can see, as example, on Adventist.org, there is a 404 for `https://www.adventist.org/wp-content/plugins/alps-gutenberg-blocks/src/front.js`.

Please find why this is missing or even linked, and resolve this error.

**Comment by YauheniKapliarchuk** [comment]
Hi @designerbrent 

I found this file on another branch! So I am going to add this file on master branch

**Comment by designerbrent** [comment]
What is in the file?

**Comment by YauheniKapliarchuk** [comment]
https://github.com/adventistchurch/alps-gutenberg-blocks/pull/48/files#diff-7044cc21c32a10c16d5b873fe4774b9e37eda03f51b10a76e886c4cfcdc73c01R1

On this commit I found this. We add this for adding right columns for media-block component

**Comment by YauheniKapliarchuk** [comment]
And I guess it was not merged correctly with the master branch

**Comment by YauheniKapliarchuk** [comment]
We did it for checking wordpress sidebar is turn on or off
