### ISSUE TITLE
Enable html in ALPS Media Block

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#69]
We need to enable HTML in the rendering of the ALPS Media Block. When you include html in the description field, it works in the editor view, but not on the front end.

![2021-05-27 at 10 22 AM](https://user-images.githubusercontent.com/132864/119843465-95795380-bed5-11eb-9b2e-4f9cbcf9cf87.jpg)

**Comment by designerbrent** [comment]
This is a problem in the old version and the new refactored `2.0.0` version.

**Comment by YauheniKapliarchuk** [comment]
Hi @designerbrent!

You can see my PR here - https://github.com/adventistchurch/alps-gutenberg-blocks/pull/71

Thanks!

**Comment by designerbrent** [comment]
This is fixed in version `2.0.1`.
