### ISSUE TITLE
Missing i18n Phrases 

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-gutenberg-blocks#75]
**Version of ALPS for Wordpress**
v3

**Describe the bug**
I've been working with someone to translate the theme into Korean. He let me know that there are still a few missing phrases in the i18n files. 

In the Media Testimonies block, the "Read More" and "Watch Video", and "See All Stories" phrases are either missing or unable to be replaced. 

**Screenshots**
![2021-09-09-09-31-01](https://user-images.githubusercontent.com/132864/139586110-f491334c-4db6-4df1-ad48-193eaf0f7675.png)

**Comment by YauheniKapliarchuk** [comment]
Hi,

PRfor resolve this issue: https://github.com/adventistchurch/alps-wordpress/pull/618

thanks,
Best Regards!

CC: @daniel-eesti @hans-olson @johnrbeckett
