### ISSUE TITLE
New design of ALPS Quote block

### ISSUE THREAD

**Issue by daniel-eesti** [adventistchurch/alps-gutenberg-blocks#87]
ALPS Quote block has bags and doesn't meet our UX requirements; we need to redesign it.

**New design** (developer will get access to [Figma](https://www.figma.com/file/IIrU9CtXKkkfAlIhPtYiJK/Quotes-style?node-id=8%3A2)):

![image.png](https://images.zenhubusercontent.com/6202899afa52985a8d095480/61cb584b-b35c-4b5a-9247-74c3677d2e2b)

The way the block looks in the block editor should remain the same.

**Comment by YauheniKapliarchuk** [comment]
Hi @daniel-eesti 

I have a few questions.

0. Is this design for "Blockquote" block?
1. We should be able to have 3 different views, i.e. ticks of how the block should look on the user's side?
2. Apart from quotes, I understand that nothing should change?
3. The color of the quote is the same all the time?
4. If the settings are needed, they should be in on the side panel or on the block itself? We now have blocks where something is put down automatically or there are checkboxes in the block itself in the editor.

Thank you so much in advance!
Best Regards!

CC: @hans-olson  @johnrbeckett

**Comment by daniel-eesti** [comment]
@YauheniKapliarchuk 
0. Yes, it is for the "ALPS Blockquote" block
1. No, there is only 1 version of the quote block, the one on the screenshot in this GitHub issue. Here is the link to the exact block on Figma: https://www.figma.com/file/IIrU9CtXKkkfAlIhPtYiJK/Quotes-style?node-id=8%3A2
2. Yes, this task is only about redesigning "ALPS Blockquote" block
3. Yes, follow exact colors which you can find in the Figma
4. Block in the editor stays exactly the same as it is right now. Regarding side panel: currently there are 2 settings: Extend Quote and Strong Quote. Non of them are needed anymore. So, there should be no additional settings in the side panel for this block.

**Comment by YauheniKapliarchuk** [comment]
Thank you Daniel,

one more question:
- could you please add mobile and tablet view into figma file?

Thanks!

@daniel-eesti

**Comment by daniel-eesti** [comment]
@YauheniKapliarchuk I have already requested it from the designer. It will be added to the same Figma board.

**Comment by daniel-eesti** [comment]
@YauheniKapliarchuk Done. Please check it out. It has only a desktop and mobile. Tablet is the same as the desktop.

**Comment by YauheniKapliarchuk** [comment]
Hi, 

PR for new styles for BlockQuote Gutenberg Block.
https://github.com/adventistchurch/alps/pull/575

thanks,
Best Regards!

**Comment by daniel-eesti** [comment]
This block's design on production differs from the one in the task description.

![image.png](https://images.zenhubusercontent.com/6202899afa52985a8d095480/25530c64-da5b-4338-a1a4-78da5a350d02)

**Comment by daniel-eesti** [comment]
Released to production with two bugs:
1. Empty citation bug: if the Citation field is empty, there is an empty space instead of citation text.
![image.png](https://images.zenhubusercontent.com/6202899afa52985a8d095480/273ca8de-5c5f-41aa-852c-4041bf1d1e4b)
2. Quote's body color mismatches with Figma's design. The color of the quote's body text and citation text should be the same (light blue, not dark blue).

Example of the bug: https://www.adventist.org/7-powerful-prayers-in-the-bible-and-what-we-can-learn-from-them/

**Comment by YauheniKapliarchuk** [comment]
Hi, @daniel-eesti 
could you please test again it, I didn't have access to sites for testing?

Thanks, 
Best Regards!

**Comment by daniel-eesti** [comment]
@YauheniKapliarchuk unfortunately the empty citation bug is still there.

![image](https://user-images.githubusercontent.com/98831022/208459929-cfe15e85-687c-4b90-83e6-734b1b7a588b.png)

**Comment by daniel-eesti** [comment]
It is fixed now. Thank you.

**Comment by YauheniKapliarchuk** [comment]
Hi everyone,

if you have any questions about this issue, please reopen it.

Thanks,
Best Regards!

CC: @hans-olson @daniel-eesti @johnrbeckett
