### ISSUE TITLE
CLS issues | Research

### ISSUE THREAD

**Issue by daniel-eesti** [adventistchurch/alps-gutenberg-blocks#88]
Post's featured image and image block(?) causes a **Cumulative Layout Shift** of more than 0.1 on these pages:

https://www.adventist.org/nature-of-humanity/four-lessons-from-the-potters-house/ - **0.21**
https://www.adventist.org/gift-of-prophecy/the-gift-of-prophecy/ - **0.19**
https://www.adventist.org/world-church/east-central-africa/ - **0.16**

**Comment by YauheniKapliarchuk** [comment]
Hi everyone,
@daniel-eesti confirmed fix on his sites.

Thanks,
Best Regards!

@johnrbeckett @designerbrent
